#!/usr/bin/env bash

# ================================================================================
# =                                     COPY                                     =
# ================================================================================

NAME=${0##*/}

SOURCES=()
TARGETS=()

declare -A SOURCES_MAPPING=(
    [zshrc]="$HOME/.zshrc"
    [zshenv]="$HOME/.zshenv"
    [zshenvlocal]="$HOME/.zshenv.local"
    [nvim]="$HOME/.config/nvim/"
    [yazi]="$HOME/.config/yazi/"
)

usage() {
    echo "Usage: $NAME <source>... <target>... [-h|--help]"
    echo "  sources: zshrc zshenv zshenvlocal nvim yazi"
    echo "  targets: pi kali"
}

parse_args() {
    if (($# == 0)); then
        usage >&2
        exit 1
    fi

    while (($# > 0)); do
        case "$1" in
            zshrc | zshenv | zshenvlocal | nvim | yazi)
                SOURCES+=("$1")
                ;;
            pi | kali)
                TARGETS+=("$1")
                ;;
            -h | --help)
                usage
                exit
                ;;
            *)
                usage >&2
                exit 1
                ;;
        esac
        shift
    done
}

copy_files() {
    local source target
    for source in "${SOURCES[@]}"; do
        for target in "${TARGETS[@]}"; do
            rsync --verbose --recursive --copy-links \
                "${SOURCES_MAPPING[$source]}" \
                "${target}:${SOURCES_MAPPING[$source]}"
        done
    done
}

main() {
    parse_args "$@"
    copy_files
}

main "$@"
