#!/usr/bin/env bash

# ================================================================================
# =                                   DOTSYNC                                    =
# ================================================================================

read -ra MACHINES <<<"$(python "$HOME/inventory/parser.py" machines)"

sync() {
    for machine in "${MACHINES[@]}"; do
        [[ "$machine" == "$HOSTNAME" ]] && continue
        ssh "$machine" 'cd $HOME/dotfiles && git pull origin master && cd $HOME/bash/scripts && git pull origin master && bash mksym'
    done
}

main() {
    sync
}

main
