#!/usr/bin/env bash

# ================================================================================
# =                                   GETMUSIC                                   =
# ================================================================================

# Downloads YouTube Music playlist using yt-dlp
# Skips existing files in output directory
# Copies playlist to pi using rsync
# Circumvents headless pi cookie issue

set -eou pipefail

OUTPUT="$HOME/music"

require_wsl() {
    if [[ "$HOSTNAME" != "wsl" ]]; then
        echo "This script should only be run on wsl" >&2
        exit 1
    fi
}

check_for_yt-dlp() {
    if ! command -v yt-dlp &>/dev/null; then
        echo "yt-dlp not found" >&2
        exit 1
    fi
}

run_yt-dlp() {
    mkdir --parents "$OUTPUT"

    yt-dlp --cookies-from-browser firefox \
        --extract-audio \
        --audio-format mp3 \
        --no-overwrites \
        --sleep-interval 2 --max-sleep-interval 5 \
        --download-archive "${OUTPUT}/archive.txt" \
        --output "${OUTPUT}/%(artist)s - %(title)s.%(ext)s" \
        "$YOUTUBE_MUSIC_PLAYLIST" \
        || true
}

copy_to_pi() {
    rsync --archive --verbose --progress "${OUTPUT}/" "pi:/srv/navidrome/music"
}

main() {
    require_wsl
    check_for_yt-dlp
    run_yt-dlp
    copy_to_pi
}

main
