#!/usr/bin/env bash

# ================================================================================
# =                                   INVSYNC                                    =
# ================================================================================

read -ra MACHINES <<<"$(python3 "$HOME/inventory/parser.py" machines)"

invsync() {
    for machine in "${MACHINES[@]}"; do
        [[ "$machine" == "$HOSTNAME" ]] && continue
        ssh "$machine" '
            cd $HOME/inventory && git pull origin master
            cd $HOME/dotfiles && git pull origin master
            cd $HOME/bash/scripts && git pull origin master && bash mksym
        '
    done
}

main() {
    invsync
}

main
