#!/usr/bin/env bash

# ================================================================================
# =                                   LINKSYNC                                   =
# ================================================================================

linksync() {
    while read -r source target sudo; do
        local cmd=()
        [[ -L "$target" ]] && continue                           # skip if symlink already exists
        [[ "$sudo" == "true" ]] && cmd=(sudo)                    # add sudo to command if sudo is true
        mkdir --parents "$(dirname "$source")"                   # ensure dotfiles destination dir exists
        [[ -e "$target" ]] && "${cmd[@]}" mv "$target" "$source" # move existing config into dotfiles
        "${cmd[@]}" mkdir --parents "$(dirname "$target")"       # ensure target parent dir exists
        "${cmd[@]}" ln --symbolic --force "$source" "$target"    # create symlink from dotfiles to target
    done < <(python3 "$HOME/inventory/parser.py" links "$HOSTNAME")
}

main() {
    linksync
}

main
