#!/usr/bin/env bash

# ================================================================================
# =                                    MKSYM                                     =
# ================================================================================

declare -A SYMLINK_MAPPING

SYMLINK_MAPPING=(
    [$HOME/dotfiles/atuin]="$HOME/.config/atuin"
    [$HOME/dotfiles/direnv]="$HOME/.config/direnv"
    [$HOME/dotfiles/fzf]="$HOME/.config/fzf"
    [$HOME/dotfiles/git/.gitconfig]="$HOME/.gitconfig"
    [$HOME/dotfiles/helix]="$HOME/.config/helix"
    [$HOME/dotfiles/homepage]="$HOME/.config/homepage"
    [$HOME/dotfiles/kak]="$HOME/.config/kak"
    [$HOME/dotfiles/nvim]="$HOME/.config/nvim"
    [$HOME/dotfiles/sqlite/.sqliterc]="$HOME/.config/nvim"
    [$HOME/dotfiles/ssh/config]="$HOME/.sqliterc"
    [$HOME/dotfiles/yazi]="$HOME/.config/yazi"
    [$HOME/dotfiles/zsh/.xprofile]="$HOME/.xprofile"
    [$HOME/dotfiles/zellij]="$HOME/.config/zellij"
    [$HOME/dotfiles/zsh/.zprofile]="$HOME/.zprofile"
    [$HOME/dotfiles/zsh/.zshenv]="$HOME/.zshenv"
    [$HOME/dotfiles/zsh/.zshenv.local]="$HOME/.zshenv.local"
    [$HOME/dotfiles/zsh/.zshrc]="$HOME/.zshrc"
)

create_symlinks() {
    for source in "${!SYMLINK_MAPPING[@]}"; do
        destination="${SYMLINK_MAPPING[$source]}"
        [[ -e $destination ]] && rm --recursive --force "$destination"
        mkdir --parents "$(dirname "$destination")"
        ln --symbolic --force "$source" "$destination"
    done
}

main() {
    create_symlinks
}

main
