#!/usr/bin/env bash

# ================================================================================
# =                                    MKSYM                                     =
# ================================================================================

create_symlinks() {
    while read -r source target; do
        [[ -e $target ]] && rm --recursive --force "$target"
        mkdir --parents "$(dirname "$target")"
        ln --symbolic --force "$source" "$target"
    done < <(python "$HOME/inventory/parser.py" links "$HOSTNAME")
}

main() {
    create_symlinks
}

main
